{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "httpbin.fullname" . }}-allow-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ include "httpbin.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80
{{- end }}

