apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpbin.fullname" . }}
  labels:
    app: {{ include "httpbin.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "httpbin.name" . }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80

